/**
 * API Fetch Wrapper for EGDesk Tunneling
 *
 * This wrapper automatically prepends NEXT_PUBLIC_EGDESK_BASE_PATH to relative URLs.
 * This is necessary because Next.js basePath does NOT automatically apply to
 * client-side fetch() calls - it's a known limitation.
 *
 * Generated by @egdesk/next-api-plugin
 */

const basePath = process.env.NEXT_PUBLIC_EGDESK_BASE_PATH || '';

/**
 * Fetch wrapper that handles basePath for tunneled environments
 *
 * @example
 * // ❌ Wrong - will return 404 in tunneled environment
 * fetch('/api/transactions')
 *
 * @example
 * // ✅ Correct - automatically prepends basePath
 * apiFetch('/api/transactions')
 *
 * @param path - The API path (e.g., '/api/transactions')
 * @param options - Standard fetch options
 */
export async function apiFetch(path: string, options?: RequestInit): Promise<Response> {
  // Automatically prepend basePath to relative URLs
  const url = path.startsWith('/') && !path.startsWith('//')
    ? `${basePath}${path}`
    : path;

  return fetch(url, options);
}
