/**
 * API Fetch Wrapper for EGDesk Tunneling
 *
 * Re-exports apiFetch from egdesk-helpers.ts (canonical source).
 * Use apiFetch for client-side /api/* calls — Next.js basePath does not apply to fetch().
 *
 * Generated by @egdesk/next-api-plugin
 */

export { apiFetch, getEgdeskBasePath } from '../../egdesk-helpers';
