/**
 * EGDesk visitor Google helpers (published-site visitors).
 *
 * Visitors become EGDesk Auth users. Login is brokered by EGDesk so this
 * site never receives SUPABASE_URL or the anon key.
 * The opaque session is bound to this site origin and will not work on
 * another published site that shares the same EGDesk.
 *
 * Import this file only from pages that need visitor Google.
 *
 * Generated by @egdesk/next-api-plugin.
 */

import { apiFetch } from './egdesk-helpers';

const VISITOR_SESSION_KEY = 'egdesk_visitor_session';

export const VISITOR_GOOGLE_OAUTH_SCOPES = [
  'https://www.googleapis.com/auth/userinfo.email',
  'https://www.googleapis.com/auth/userinfo.profile',
  'https://www.googleapis.com/auth/drive.file',
  'https://www.googleapis.com/auth/spreadsheets',
  'https://www.googleapis.com/auth/documents',
  'https://www.googleapis.com/auth/presentations',
  'openid',
] as const;

function getVisitorSessionId(): string | null {
  if (typeof window === 'undefined') return null;
  return window.localStorage.getItem(VISITOR_SESSION_KEY);
}

function setVisitorSessionId(sessionId: string | null): void {
  if (typeof window === 'undefined') return;
  if (sessionId) window.localStorage.setItem(VISITOR_SESSION_KEY, sessionId);
  else window.localStorage.removeItem(VISITOR_SESSION_KEY);
}

async function parseEgdeskJson(response: Response): Promise<any> {
  const result = await response.json().catch(() => null);
  if (!response.ok) {
    const errMsg =
      result && typeof result === 'object' && typeof result.error === 'string'
        ? result.error
        : `Request failed (${response.status})`;
    throw new Error(errMsg);
  }
  return result;
}

function visitorOriginHeaders(): Record<string, string> {
  if (typeof window === 'undefined') return {};
  return { 'X-Visitor-Origin': window.location.origin };
}

async function callVisitorAuth(tool: string, args: Record<string, unknown> = {}) {
  const response = await apiFetch('/__visitor_auth_proxy', {
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...visitorOriginHeaders() },
    body: JSON.stringify({ tool, arguments: args }),
  });
  return parseEgdeskJson(response);
}

async function callVisitorGoogle(tool: string, args: Record<string, unknown> = {}) {
  const sessionId = getVisitorSessionId();
  if (!sessionId) {
    throw new Error('Visitor is not signed in. Call startVisitorGoogleLogin() first.');
  }
  const response = await apiFetch('/__visitor_google_proxy', {
    method: 'POST',
    headers: {
      'Content-Type': 'application/json',
      Authorization: `Bearer ${sessionId}`,
      ...visitorOriginHeaders(),
    },
    body: JSON.stringify({ tool, arguments: args }),
  });
  return parseEgdeskJson(response);
}

/**
 * Sign a website visitor in with Google via EGDesk.
 * Creates/uses an EGDesk user; Google tokens stay under that user_id on EGDesk.
 */
export async function startVisitorGoogleLogin(options: {
  next?: string;
  forceConsent?: boolean;
} = {}) {
  if (typeof window === 'undefined') {
    throw new Error('startVisitorGoogleLogin() must run in the browser');
  }
  const next =
    options.next && options.next.startsWith('/') ? options.next : window.location.pathname;
  const returnTo = new URL('/auth/callback', window.location.origin);
  returnTo.searchParams.set('next', next);
  const egdeskPublicUrl =
    process.env.NEXT_PUBLIC_EGDESK_API_URL || 'http://localhost:8080';

  const result = await callVisitorAuth('start', {
    returnTo: returnTo.toString(),
    egdeskPublicUrl,
    forceConsent: options.forceConsent !== false,
  });
  if (!result?.authUrl) {
    throw new Error(result?.error || 'Failed to start visitor Google login');
  }
  window.location.href = result.authUrl;
}

export async function exchangeVisitorAuthCode(code: string) {
  const result = await callVisitorAuth('exchange', { code });
  if (!result?.sessionId) {
    throw new Error(result?.error || 'Failed to complete visitor login');
  }
  setVisitorSessionId(result.sessionId);
  return result;
}

export async function signOutVisitorGoogle() {
  try {
    const sessionId = getVisitorSessionId();
    if (sessionId) {
      await callVisitorAuth('logout', { sessionId });
    }
  } finally {
    setVisitorSessionId(null);
  }
}

export async function getVisitorGoogleStatus() {
  const sessionId = getVisitorSessionId();
  if (!sessionId) {
    return { connected: false, email: null, message: 'Visitor is not signed in.' };
  }
  try {
    return await callVisitorGoogle('status');
  } catch {
    return { connected: false, email: null, message: 'Visitor is not signed in.' };
  }
}

export async function listVisitorDriveFiles(options: { pageSize?: number; query?: string } = {}) {
  return callVisitorGoogle('listDriveFiles', options);
}

export async function getVisitorSheetRange(spreadsheetId: string, range: string) {
  return callVisitorGoogle('getSheetRange', { spreadsheetId, range });
}
