/**
 * EGDesk Helper Functions for Next.js
 *
 * Type-safe helpers for EGDesk user data, FinanceHub (banks, cards, Hometax), and browser recorder replay.
 * Works in both client and server components.
 *
 * Generated by @egdesk/next-api-plugin
 */

import { EGDESK_CONFIG } from './egdesk.config';

/**
 * Parse EGDesk MCP `/tools/call` JSON so `error` is shown even when HTTP status is 500.
 */
async function parseEgdeskMcpToolResponse(response: Response): Promise<any> {
  const result = await response.json().catch(() => null);

  if (result && typeof result === 'object' && result.success === false) {
    const errMsg =
      typeof result.error === 'string'
        ? result.error
        : result.error != null
          ? String(result.error)
          : 'Tool call failed';
    throw new Error(errMsg);
  }

  if (!response.ok) {
    let fromBody = '';
    if (result && typeof result === 'object') {
      if (typeof result.error === 'string') fromBody = result.error;
      else if (typeof (result as { message?: string }).message === 'string') {
        fromBody = (result as { message: string }).message;
      }
    }
    throw new Error(fromBody || `HTTP ${response.status}: ${response.statusText}`);
  }

  if (!result || result.success !== true) {
    throw new Error(
      result && typeof result === 'object' && typeof result.error === 'string'
        ? result.error
        : 'Tool call failed'
    );
  }

  const content = result.result?.content?.[0]?.text;
  return content ? JSON.parse(content) : null;
}

/**
 * Call EGDesk user-data MCP tool
 *
 * - Server (API routes): Calls Egdesk API directly using EGDESK_CONFIG.apiUrl and
 *   EGDESK_CONFIG.apiKey (from env NEXT_PUBLIC_EGDESK_API_URL / NEXT_PUBLIC_EGDESK_API_KEY)
 *   so relative URLs and tunnel base path are not an issue.
 * - Client (browser): Uses /__user_data_proxy so CORS and tunnel base path still work.
 */
export async function callUserDataTool(
  toolName: string,
  args: Record<string, any> = {}
): Promise<any> {
  const body = JSON.stringify({ tool: toolName, arguments: args });
  const headers: Record<string, string> = {
    'Content-Type': 'application/json'
  };

  const isServer = typeof window === 'undefined';

  let response: Response;
  if (isServer) {
    // API routes: call Egdesk directly (relative URL is invalid in Node)
    const apiUrl =
      (typeof process !== 'undefined' && process.env?.NEXT_PUBLIC_EGDESK_API_URL) ||
      EGDESK_CONFIG.apiUrl;
    const apiKey =
      (typeof process !== 'undefined' && process.env?.NEXT_PUBLIC_EGDESK_API_KEY) ||
      EGDESK_CONFIG.apiKey;
    if (apiKey) {
      headers['X-Api-Key'] = apiKey;
    }
    response = await fetch(`${apiUrl}/user-data/tools/call`, {
      method: 'POST',
      headers,
      body
    });
  } else {
    // Browser: use proxy for CORS and tunnel base path
    response = await fetch('/__user_data_proxy', {
      method: 'POST',
      headers,
      body
    });
  }

  return parseEgdeskMcpToolResponse(response);
}

/**
 * Query table data
 */
export async function queryTable(
  tableName: string,
  options: {
    filters?: Record<string, string>;
    limit?: number;
    offset?: number;
    orderBy?: string;
    orderDirection?: 'ASC' | 'DESC';
  } = {}
) {
  return callUserDataTool('user_data_query', {
    tableName,
    ...options
  });
}

/**
 * Search table
 */
export async function searchTable(
  tableName: string,
  searchQuery: string,
  limit: number = 50
) {
  return callUserDataTool('user_data_search', {
    tableName,
    searchQuery,
    limit
  });
}

/**
 * Aggregate data
 */
export async function aggregateTable(
  tableName: string,
  column: string,
  aggregateFunction: 'SUM' | 'AVG' | 'MIN' | 'MAX' | 'COUNT',
  options: {
    filters?: Record<string, string>;
    groupBy?: string;
  } = {}
) {
  return callUserDataTool('user_data_aggregate', {
    tableName,
    column,
    function: aggregateFunction,
    ...options
  });
}

/**
 * Execute raw SQL query (read-only, SELECT only)
 */
export async function executeSQL(query: string) {
  return callUserDataTool('user_data_sql_query', { query });
}

/**
 * List all available tables
 */
export async function listTables() {
  return callUserDataTool('user_data_list_tables', {});
}

/**
 * Get table schema
 */
export async function getTableSchema(tableName: string) {
  return callUserDataTool('user_data_get_schema', { tableName });
}

/**
 * Create a new table
 */
export async function createTable(
  displayName: string,
  schema: Array<{
    name: string;
    type: 'TEXT' | 'INTEGER' | 'REAL' | 'DATE';
    notNull?: boolean;
    defaultValue?: any;
  }>,
  options?: {
    description?: string;
    tableName?: string;
    uniqueKeyColumns?: string[];
    duplicateAction?: 'skip' | 'update' | 'allow' | 'replace-date-range';
  }
) {
  return callUserDataTool('user_data_create_table', {
    displayName,
    schema,
    ...options
  });
}

/**
 * Insert rows into a table
 */
export async function insertRows(
  tableName: string,
  rows: Array<Record<string, any>>
) {
  return callUserDataTool('user_data_insert_rows', {
    tableName,
    rows
  });
}

/**
 * Update rows in a table
 */
export async function updateRows(
  tableName: string,
  updates: Record<string, any>,
  options: {
    ids?: number[];
    filters?: Record<string, string>;
  }
) {
  return callUserDataTool('user_data_update_rows', {
    tableName,
    updates,
    ...options
  });
}

/**
 * Delete rows from a table
 */
export async function deleteRows(
  tableName: string,
  options: {
    ids?: number[];
    filters?: Record<string, string>;
  }
) {
  return callUserDataTool('user_data_delete_rows', {
    tableName,
    ...options
  });
}

/**
 * Delete a table
 */
export async function deleteTable(tableName: string) {
  return callUserDataTool('user_data_delete_table', { tableName });
}

/**
 * Rename a table
 */
export async function renameTable(
  tableName: string,
  newTableName: string,
  newDisplayName?: string
) {
  return callUserDataTool('user_data_rename_table', {
    tableName,
    newTableName,
    newDisplayName
  });
}

// ==========================================
// FINANCEHUB HELPERS
// ==========================================

/**
 * Call EGDesk FinanceHub MCP tool
 */
export async function callFinanceHubTool(
  toolName: string,
  args: Record<string, any> = {}
): Promise<any> {
  const body = JSON.stringify({ tool: toolName, arguments: args });
  const headers: Record<string, string> = {
    'Content-Type': 'application/json'
  };

  const isServer = typeof window === 'undefined';

  let response: Response;
  if (isServer) {
    const apiUrl =
      (typeof process !== 'undefined' && process.env?.NEXT_PUBLIC_EGDESK_API_URL) ||
      EGDESK_CONFIG.apiUrl;
    const apiKey =
      (typeof process !== 'undefined' && process.env?.NEXT_PUBLIC_EGDESK_API_KEY) ||
      EGDESK_CONFIG.apiKey;
    if (apiKey) {
      headers['X-Api-Key'] = apiKey;
    }
    response = await fetch(`${apiUrl}/financehub/tools/call`, {
      method: 'POST',
      headers,
      body
    });
  } else {
    response = await fetch('/__financehub_proxy', {
      method: 'POST',
      headers,
      body
    });
  }

  return parseEgdeskMcpToolResponse(response);
}

/**
 * List all registered banks and card companies
 */
export async function listBanks() {
  return callFinanceHubTool('financehub_list_banks', {});
}

/**
 * List bank accounts with balances
 */
export async function listAccounts(options: {
  bankId?: string;
  isActive?: boolean;
} = {}) {
  return callFinanceHubTool('financehub_list_accounts', options);
}

/**
 * Query bank transactions
 */
export async function queryBankTransactions(options: {
  accountId?: string;
  bankId?: string;
  startDate?: string;
  endDate?: string;
  category?: string;
  minAmount?: number;
  maxAmount?: number;
  searchText?: string;
  limit?: number;
  offset?: number;
  orderBy?: 'date' | 'amount' | 'balance';
  orderDir?: 'asc' | 'desc';
} = {}) {
  return callFinanceHubTool('financehub_query_transactions', options);
}

/**
 * Query card transactions (NEW)
 */
export async function queryCardTransactions(options: {
  accountId?: string;
  cardCompanyId?: string;
  cardNumber?: string;
  merchantName?: string;
  startDate?: string;
  endDate?: string;
  category?: string;
  minAmount?: number;
  maxAmount?: number;
  includeCancelled?: boolean;
  limit?: number;
  offset?: number;
  orderBy?: 'date' | 'amount';
  orderDir?: 'asc' | 'desc';
} = {}) {
  return callFinanceHubTool('financehub_query_card_transactions', options);
}

/**
 * Get transaction statistics
 */
export async function getTransactionStats(options: {
  accountId?: string;
  bankId?: string;
  startDate?: string;
  endDate?: string;
} = {}) {
  return callFinanceHubTool('financehub_get_statistics', options);
}

/**
 * Get monthly breakdown of deposits/withdrawals
 */
export async function getMonthlySummary(options: {
  accountId?: string;
  bankId?: string;
  year?: number;
  months?: number;
} = {}) {
  return callFinanceHubTool('financehub_get_monthly_summary', options);
}

/**
 * Get overall stats (banks, accounts, transactions, balances)
 */
export async function getOverallStats() {
  return callFinanceHubTool('financehub_get_overall_stats', {});
}

/**
 * Get bank/card sync operation history (sync_operations table)
 */
export async function getSyncHistory(limit: number = 50) {
  return callFinanceHubTool('financehub_get_sync_history', { limit });
}

/**
 * List Hometax business connections (hometax_connections: counts, spreadsheet URLs, status)
 */
export async function listHometaxConnections() {
  return callFinanceHubTool('financehub_list_hometax_connections', {});
}

/**
 * Query electronic tax invoices synced from Hometax (tax_invoices table)
 */
export async function queryTaxInvoices(options: {
  businessNumber?: string;
  invoiceType?: 'sales' | 'purchase';
  startDate?: string;
  endDate?: string;
  limit?: number;
  offset?: number;
} = {}) {
  return callFinanceHubTool('financehub_query_tax_invoices', options);
}

/**
 * Query cash receipts synced from Hometax (cash_receipts table)
 */
export async function queryCashReceipts(options: {
  businessNumber?: string;
  startDate?: string;
  endDate?: string;
  limit?: number;
  offset?: number;
} = {}) {
  return callFinanceHubTool('financehub_query_cash_receipts', options);
}

/**
 * Get Hometax Excel import sync history (hometax_sync_operations). Not the same as getSyncHistory (banks/cards).
 */
export async function getHometaxSyncHistory(limit: number = 50) {
  return callFinanceHubTool('financehub_get_hometax_sync_history', { limit });
}

// ==========================================
// BROWSER RECORDING HELPERS
// ==========================================

/**
 * Call EGDesk Browser Recording MCP tool (saved recorder tests, replay with optional dates).
 *
 * - Server: `POST {apiUrl}/browser-recording/tools/call`
 * - Client: `POST /__browser_recording_proxy` (see proxy.ts / middleware)
 */
export async function callBrowserRecordingTool(
  toolName: string,
  args: Record<string, any> = {}
): Promise<any> {
  const body = JSON.stringify({ tool: toolName, arguments: args });
  const headers: Record<string, string> = {
    'Content-Type': 'application/json'
  };

  const isServer = typeof window === 'undefined';

  let response: Response;
  if (isServer) {
    const apiUrl =
      (typeof process !== 'undefined' && process.env?.NEXT_PUBLIC_EGDESK_API_URL) ||
      EGDESK_CONFIG.apiUrl;
    const apiKey =
      (typeof process !== 'undefined' && process.env?.NEXT_PUBLIC_EGDESK_API_KEY) ||
      EGDESK_CONFIG.apiKey;
    if (apiKey) {
      headers['X-Api-Key'] = apiKey;
    }
    response = await fetch(`${apiUrl}/browser-recording/tools/call`, {
      method: 'POST',
      headers,
      body
    });
  } else {
    response = await fetch('/__browser_recording_proxy', {
      method: 'POST',
      headers,
      body
    });
  }

  return parseEgdeskMcpToolResponse(response);
}

/** List saved *.spec.js files in the EGDesk browser-recorder-tests output folder */
export async function listBrowserRecordingTests() {
  return callBrowserRecordingTool('browser_recording_list_saved_tests', {});
}

/** Inspect a spec for date-picker replay options */
export async function getBrowserRecordingReplayOptions(testFile: string) {
  return callBrowserRecordingTool('browser_recording_get_replay_options', { testFile });
}

export type BrowserRecordingRunOptions = {
  startDate?: string;
  endDate?: string;
  datePickersByIndex?: string[];
};

/** Replay a saved recording in Chrome */
export async function runBrowserRecording(
  testFile: string,
  options: BrowserRecordingRunOptions = {}
) {
  return callBrowserRecordingTool('browser_recording_run', {
    testFile,
    ...options
  });
}
