/**
 * EGDesk User Data Helper Functions for Next.js
 *
 * Type-safe helpers for accessing EGDesk user data.
 * Works in both client and server components.
 *
 * Generated by @egdesk/next-api-plugin
 */

import { EGDESK_CONFIG } from './egdesk.config';

/**
 * Call EGDesk user-data MCP tool
 *
 * - Server (API routes): Calls Egdesk API directly using EGDESK_CONFIG.apiUrl and
 *   EGDESK_CONFIG.apiKey (from env NEXT_PUBLIC_EGDESK_API_URL / NEXT_PUBLIC_EGDESK_API_KEY)
 *   so relative URLs and tunnel base path are not an issue.
 * - Client (browser): Uses /__user_data_proxy so CORS and tunnel base path still work.
 */
export async function callUserDataTool(
  toolName: string,
  args: Record<string, any> = {}
): Promise<any> {
  const body = JSON.stringify({ tool: toolName, arguments: args });
  const headers: Record<string, string> = {
    'Content-Type': 'application/json'
  };

  const isServer = typeof window === 'undefined';

  let response: Response;
  if (isServer) {
    // API routes: call Egdesk directly (relative URL is invalid in Node)
    const apiUrl =
      (typeof process !== 'undefined' && process.env?.NEXT_PUBLIC_EGDESK_API_URL) ||
      EGDESK_CONFIG.apiUrl;
    const apiKey =
      (typeof process !== 'undefined' && process.env?.NEXT_PUBLIC_EGDESK_API_KEY) ||
      EGDESK_CONFIG.apiKey;
    if (apiKey) {
      headers['X-Api-Key'] = apiKey;
    }
    response = await fetch(`${apiUrl}/user-data/tools/call`, {
      method: 'POST',
      headers,
      body
    });
  } else {
    // Browser: use proxy for CORS and tunnel base path
    response = await fetch('/__user_data_proxy', {
      method: 'POST',
      headers,
      body
    });
  }

  if (!response.ok) {
    throw new Error(`HTTP ${response.status}: ${response.statusText}`);
  }

  const result = await response.json();

  if (!result.success) {
    throw new Error(result.error || 'Tool call failed');
  }

  // Parse MCP response format
  const content = result.result?.content?.[0]?.text;
  return content ? JSON.parse(content) : null;
}

/**
 * Query table data
 */
export async function queryTable(
  tableName: string,
  options: {
    filters?: Record<string, string>;
    limit?: number;
    offset?: number;
    orderBy?: string;
    orderDirection?: 'ASC' | 'DESC';
  } = {}
) {
  return callUserDataTool('user_data_query', {
    tableName,
    ...options
  });
}

/**
 * Search table
 */
export async function searchTable(
  tableName: string,
  searchQuery: string,
  limit: number = 50
) {
  return callUserDataTool('user_data_search', {
    tableName,
    searchQuery,
    limit
  });
}

/**
 * Aggregate data
 */
export async function aggregateTable(
  tableName: string,
  column: string,
  aggregateFunction: 'SUM' | 'AVG' | 'MIN' | 'MAX' | 'COUNT',
  options: {
    filters?: Record<string, string>;
    groupBy?: string;
  } = {}
) {
  return callUserDataTool('user_data_aggregate', {
    tableName,
    column,
    function: aggregateFunction,
    ...options
  });
}

/**
 * Execute raw SQL query
 */
export async function executeSQL(query: string) {
  return callUserDataTool('user_data_sql_query', { query });
}

/**
 * List all available tables
 */
export async function listTables() {
  return callUserDataTool('user_data_list_tables', {});
}

/**
 * Get table schema
 */
export async function getTableSchema(tableName: string) {
  return callUserDataTool('user_data_get_schema', { tableName });
}
