/**
 * EGDesk Helper Functions for Next.js
 *
 * Type-safe helpers for EGDesk user data, FinanceHub (banks, cards, Hometax, promissory notes),
 * internal knowledge / business identity / company research (MCP), Korean law (MCP), and browser recorder replay.
 * Works in both client and server components.
 *
 * Generated by @egdesk/next-api-plugin — do not edit by hand.
 *
 * Schema files:
 *  - egdesk.schema.ts  — committed seed schema (edit this; commit to git)
 *  - egdesk.config.ts  — auto-generated runtime snapshot (gitignored; do not edit)
 */

import { EGDESK_CONFIG } from './egdesk.config';

/**
 * Resolve EGDesk tunnel basePath for client-side fetch.
 * Next.js basePath does NOT apply to raw fetch() — prepend manually in production.
 */
export function getEgdeskBasePath(): string {
  if (typeof window === 'undefined') {
    return (
      (typeof process !== 'undefined' && process.env?.NEXT_PUBLIC_EGDESK_BASE_PATH) ||
      (typeof process !== 'undefined' && process.env?.EGDESK_BASE_PATH) ||
      ''
    );
  }

  const fromEnv =
    (typeof process !== 'undefined' && process.env?.NEXT_PUBLIC_EGDESK_BASE_PATH) || '';
  if (fromEnv) return fromEnv;

  // Fallback: detect /t/{tunnelId}/p/{projectName} from the current URL
  const parts = window.location.pathname.split('/').filter(Boolean);
  if (parts[0] === 't' && parts.length >= 4 && parts[2] === 'p') {
    return `/${parts.slice(0, 4).join('/')}`;
  }
  return '';
}

/**
 * Fetch wrapper that prepends EGDesk basePath to relative URLs.
 * Use for /api/* routes and /__*_proxy paths in client components.
 */
export async function apiFetch(path: string, options?: RequestInit): Promise<Response> {
  const basePath = getEgdeskBasePath();
  const url =
    path.startsWith('/') && !path.startsWith('//') ? `${basePath}${path}` : path;
  return fetch(url, options);
}

/** Build EGDesk routing headers (project-id + env) for server-side direct calls. */
function buildServerEgdeskHeaders(): Record<string, string> {
  const headers: Record<string, string> = { 'Content-Type': 'application/json' };
  const apiKey =
    (typeof process !== 'undefined' && process.env?.NEXT_PUBLIC_EGDESK_API_KEY) ||
    EGDESK_CONFIG.apiKey;
  const projectId =
    typeof process !== 'undefined' ? process.env?.NEXT_PUBLIC_EGDESK_PROJECT_ID : undefined;
  const egdeskEnv =
    typeof process !== 'undefined' ? process.env?.NEXT_PUBLIC_EGDESK_ENV : undefined;
  if (apiKey) headers['X-Api-Key'] = apiKey;
  if (projectId) headers['X-EGDesk-Project-Id'] = projectId;
  if (egdeskEnv) headers['X-EGDesk-Env'] = egdeskEnv;
  return headers;
}

/**
 * Parse EGDesk MCP `/tools/call` JSON so `error` is shown even when HTTP status is 500.
 */
async function parseEgdeskMcpToolResponse(response: Response): Promise<any> {
  const result = await response.json().catch(() => null);

  if (result && typeof result === 'object' && result.success === false) {
    const errMsg =
      typeof result.error === 'string'
        ? result.error
        : result.error != null
          ? String(result.error)
          : 'Tool call failed';
    throw new Error(errMsg);
  }

  if (!response.ok) {
    let fromBody = '';
    if (result && typeof result === 'object') {
      if (typeof result.error === 'string') fromBody = result.error;
      else if (typeof (result as { message?: string }).message === 'string') {
        fromBody = (result as { message: string }).message;
      }
    }
    throw new Error(fromBody || `HTTP ${response.status}: ${response.statusText}`);
  }

  if (!result || result.success !== true) {
    throw new Error(
      result && typeof result === 'object' && typeof result.error === 'string'
        ? result.error
        : 'Tool call failed'
    );
  }

  const content = result.result?.content?.[0]?.text;
  return content ? JSON.parse(content) : null;
}

/**
 * Call EGDesk user-data MCP tool
 *
 * - Server (API routes): Calls Egdesk API directly using EGDESK_CONFIG.apiUrl and
 *   EGDESK_CONFIG.apiKey (from env NEXT_PUBLIC_EGDESK_API_URL / NEXT_PUBLIC_EGDESK_API_KEY)
 *   so relative URLs and tunnel base path are not an issue.
 * - Client (browser): Uses /__user_data_proxy so CORS and tunnel base path still work.
 */
export async function callUserDataTool(
  toolName: string,
  args: Record<string, any> = {}
): Promise<any> {
  const body = JSON.stringify({ tool: toolName, arguments: args });

  const isServer = typeof window === 'undefined';

  let response: Response;
  if (isServer) {
    // API routes: call Egdesk directly (relative URL is invalid in Node)
    const apiUrl =
      (typeof process !== 'undefined' && process.env?.NEXT_PUBLIC_EGDESK_API_URL) ||
      EGDESK_CONFIG.apiUrl;
    response = await fetch(`${apiUrl}/user-data/tools/call`, {
      method: 'POST',
      headers: buildServerEgdeskHeaders(),
      body
    });
  } else {
    // Browser: use proxy for CORS and tunnel base path (proxy.ts injects routing headers)
    response = await apiFetch('/__user_data_proxy', {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body
    });
  }

  return parseEgdeskMcpToolResponse(response);
}

/**
 * Query table data
 */
export async function queryTable(
  tableName: string,
  options: {
    filters?: Record<string, string>;
    limit?: number;
    offset?: number;
    orderBy?: string;
    orderDirection?: 'ASC' | 'DESC';
  } = {}
) {
  return callUserDataTool('user_data_query', {
    tableName,
    ...options
  });
}

/**
 * Search table
 */
export async function searchTable(
  tableName: string,
  searchQuery: string,
  limit: number = 50
) {
  return callUserDataTool('user_data_search', {
    tableName,
    searchQuery,
    limit
  });
}

/**
 * Aggregate data
 */
export async function aggregateTable(
  tableName: string,
  column: string,
  aggregateFunction: 'SUM' | 'AVG' | 'MIN' | 'MAX' | 'COUNT',
  options: {
    filters?: Record<string, string>;
    groupBy?: string;
  } = {}
) {
  return callUserDataTool('user_data_aggregate', {
    tableName,
    column,
    function: aggregateFunction,
    ...options
  });
}

/**
 * Execute raw SQL query (read-only, SELECT only).
 * Supports JOINs — use listTables() and getTableSchema() to discover tables/columns first.
 * For structured multi-table joins, prefer joinTables().
 */
export async function executeSQL(query: string) {
  return callUserDataTool('user_data_sql_query', { query });
}

/**
 * Join one or more tables and query combined rows.
 * Use listTables() and getTableSchema() first to discover table names and columns.
 *
 * @example
 * await joinTables('orders', [
 *   { table: 'customers', on: { leftColumn: 'customer_id', rightColumn: 'id' } },
 *   { table: 'products', on: { leftColumn: 'orders.product_id', rightColumn: 'id' }, joinType: 'LEFT' },
 * ]);
 */
export async function joinTables(
  fromTable: string,
  joins: Array<{
    table: string;
    on:
      | { leftColumn: string; rightColumn: string }
      | Array<{ leftColumn: string; rightColumn: string }>;
    joinType?: 'INNER' | 'LEFT' | 'RIGHT';
  }>,
  options: {
    select?: string[];
    filters?: Record<string, string>;
    limit?: number;
    offset?: number;
    orderBy?: string;
    orderDirection?: 'ASC' | 'DESC';
  } = {}
) {
  return callUserDataTool('user_data_join', {
    fromTable,
    joins,
    ...options
  });
}

/**
 * List all available tables
 */
export async function listTables() {
  return callUserDataTool('user_data_list_tables', {});
}

/**
 * Get table schema
 */
export async function getTableSchema(tableName: string) {
  return callUserDataTool('user_data_get_schema', { tableName });
}

/**
 * Create a new table
 */
export async function createTable(
  displayName: string,
  schema: Array<{
    name: string;
    type: 'TEXT' | 'INTEGER' | 'REAL' | 'DATE';
    notNull?: boolean;
    defaultValue?: any;
  }>,
  options?: {
    description?: string;
    tableName?: string;
    uniqueKeyColumns?: string[];
    duplicateAction?: 'skip' | 'update' | 'allow' | 'replace-date-range';
  }
) {
  return callUserDataTool('user_data_create_table', {
    displayName,
    schema,
    ...options
  });
}

/**
 * Insert rows into a table
 */
export async function insertRows(
  tableName: string,
  rows: Array<Record<string, any>>
) {
  return callUserDataTool('user_data_insert_rows', {
    tableName,
    rows
  });
}

/**
 * Update rows in a table
 */
export async function updateRows(
  tableName: string,
  updates: Record<string, any>,
  options: {
    ids?: number[];
    filters?: Record<string, string>;
  }
) {
  return callUserDataTool('user_data_update_rows', {
    tableName,
    updates,
    ...options
  });
}

/**
 * Delete rows from a table
 */
export async function deleteRows(
  tableName: string,
  options: {
    ids?: number[];
    filters?: Record<string, string>;
  }
) {
  return callUserDataTool('user_data_delete_rows', {
    tableName,
    ...options
  });
}

/**
 * Delete a table
 */
export async function deleteTable(tableName: string) {
  return callUserDataTool('user_data_delete_table', { tableName });
}

/**
 * Rename a table
 */
export async function renameTable(
  tableName: string,
  newTableName: string,
  newDisplayName?: string
) {
  return callUserDataTool('user_data_rename_table', {
    tableName,
    newTableName,
    newDisplayName
  });
}

// ==========================================
// FINANCEHUB HELPERS
// ==========================================

/**
 * Call EGDesk FinanceHub MCP tool
 */
export async function callFinanceHubTool(
  toolName: string,
  args: Record<string, any> = {}
): Promise<any> {
  const body = JSON.stringify({ tool: toolName, arguments: args });

  const isServer = typeof window === 'undefined';

  let response: Response;
  if (isServer) {
    const apiUrl =
      (typeof process !== 'undefined' && process.env?.NEXT_PUBLIC_EGDESK_API_URL) ||
      EGDESK_CONFIG.apiUrl;
    response = await fetch(`${apiUrl}/financehub/tools/call`, {
      method: 'POST',
      headers: buildServerEgdeskHeaders(),
      body
    });
  } else {
    response = await apiFetch('/__financehub_proxy', {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body
    });
  }

  return parseEgdeskMcpToolResponse(response);
}

/**
 * List all registered banks and card companies
 */
export async function listBanks() {
  return callFinanceHubTool('financehub_list_banks', {});
}

/**
 * List bank accounts with balances
 */
export async function listAccounts(options: {
  bankId?: string;
  isActive?: boolean;
} = {}) {
  return callFinanceHubTool('financehub_list_accounts', options);
}

/**
 * Query bank transactions
 */
export async function queryBankTransactions(options: {
  accountId?: string;
  bankId?: string;
  startDate?: string;
  endDate?: string;
  category?: string;
  minAmount?: number;
  maxAmount?: number;
  searchText?: string;
  limit?: number;
  offset?: number;
  orderBy?: 'date' | 'amount' | 'balance';
  orderDir?: 'asc' | 'desc';
} = {}) {
  return callFinanceHubTool('financehub_query_transactions', options);
}

/**
 * Query card transactions (NEW)
 */
export async function queryCardTransactions(options: {
  accountId?: string;
  cardCompanyId?: string;
  cardNumber?: string;
  merchantName?: string;
  startDate?: string;
  endDate?: string;
  category?: string;
  minAmount?: number;
  maxAmount?: number;
  includeCancelled?: boolean;
  limit?: number;
  offset?: number;
  orderBy?: 'date' | 'amount';
  orderDir?: 'asc' | 'desc';
} = {}) {
  return callFinanceHubTool('financehub_query_card_transactions', options);
}

/**
 * Get transaction statistics
 */
export async function getTransactionStats(options: {
  accountId?: string;
  bankId?: string;
  startDate?: string;
  endDate?: string;
} = {}) {
  return callFinanceHubTool('financehub_get_statistics', options);
}

/**
 * Get monthly breakdown of deposits/withdrawals
 */
export async function getMonthlySummary(options: {
  accountId?: string;
  bankId?: string;
  year?: number;
  months?: number;
} = {}) {
  return callFinanceHubTool('financehub_get_monthly_summary', options);
}

/**
 * Get overall stats (banks, accounts, transactions, balances)
 */
export async function getOverallStats() {
  return callFinanceHubTool('financehub_get_overall_stats', {});
}

/**
 * Get bank/card sync operation history (sync_operations table)
 */
export async function getSyncHistory(limit: number = 50) {
  return callFinanceHubTool('financehub_get_sync_history', { limit });
}

/**
 * List Hometax business connections (hometax_connections: counts, spreadsheet URLs, status)
 */
export async function listHometaxConnections() {
  return callFinanceHubTool('financehub_list_hometax_connections', {});
}

/**
 * Query electronic tax invoices synced from Hometax (tax_invoices table)
 */
export async function queryTaxInvoices(options: {
  businessNumber?: string;
  invoiceType?: 'sales' | 'purchase';
  startDate?: string;
  endDate?: string;
  limit?: number;
  offset?: number;
} = {}) {
  return callFinanceHubTool('financehub_query_tax_invoices', options);
}

/**
 * Query tax-exempt invoices synced from Hometax (tax_exempt_invoices table)
 */
export async function queryTaxExemptInvoices(options: {
  businessNumber?: string;
  invoiceType?: 'sales' | 'purchase';
  startDate?: string;
  endDate?: string;
  limit?: number;
  offset?: number;
} = {}) {
  return callFinanceHubTool('financehub_query_tax_exempt_invoices', options);
}

/**
 * Query cash receipts synced from Hometax (cash_receipts table)
 */
export async function queryCashReceipts(options: {
  businessNumber?: string;
  startDate?: string;
  endDate?: string;
  limit?: number;
  offset?: number;
} = {}) {
  return callFinanceHubTool('financehub_query_cash_receipts', options);
}

/**
 * Get Hometax Excel import sync history (hometax_sync_operations). Not the same as getSyncHistory (banks/cards).
 */
export async function getHometaxSyncHistory(limit: number = 50) {
  return callFinanceHubTool('financehub_get_hometax_sync_history', { limit });
}

/**
 * List per-(bank, product) bank-product tables — bank-side product data
 * downloaded from bank portals that isn't core deposit/card transactions
 * (loans, receivables, e-bills, etc.). Returns table slugs, displayName,
 * column schemas, and row counts. ALWAYS call this first to discover
 * what tables exist before calling queryBankProductTable.
 */
export async function listBankProductTables() {
  return callFinanceHubTool('financehub_list_bank_product_tables', {});
}

/**
 * Generic safe query against any per-(bank, product) table from
 * listBankProductTables. Filters use the table's exact column names
 * (snake_case). Returns rows with totalMatching, limit, offset.
 *
 * @example
 *   queryBankProductTable({
 *     tableSlug: 'ibk_loan_transactions',
 *     filters: [
 *       { column: 'account_number', op: '=', value: '306-063568-04-036' },
 *       { column: 'transaction_amount', op: '>', value: 1000000 },
 *     ],
 *     orderBy: { column: 'transaction_date', direction: 'DESC' },
 *     limit: 50,
 *   });
 */
export async function queryBankProductTable(options: {
  tableSlug: string;
  filters?: Array<{
    column: string;
    op: '=' | '!=' | '>' | '<' | '>=' | '<=' | 'like' | 'in';
    value: string | number | Array<string | number>;
  }>;
  orderBy?: { column: string; direction?: 'ASC' | 'DESC' };
  limit?: number;
  offset?: number;
  latestOnly?: boolean;
}) {
  return callFinanceHubTool('financehub_query_bank_product_table', options);
}

/**
 * Create or update a bank/card account (no credentials).
 */
export async function upsertFinanceHubAccount(account: {
  bankId: string;
  accountNumber: string;
  accountName?: string;
  customerName?: string;
  balance?: number;
  availableBalance?: number;
  currency?: string;
  accountType?: string;
  openDate?: string;
  metadata?: Record<string, unknown>;
}) {
  return callFinanceHubTool('financehub_upsert_account', account);
}

/**
 * Import bank or card transactions (deduplicated). Max 1000 per call.
 */
export async function importFinanceHubTransactions(options: {
  bankId: string;
  accountData: {
    accountNumber: string;
    accountName?: string;
    customerName?: string;
    balance?: number;
    availableBalance?: number;
    openDate?: string;
  };
  transactions: Array<Record<string, unknown>>;
  syncMetadata: {
    queryPeriodStart: string;
    queryPeriodEnd: string;
    filePath?: string;
  };
  isCard?: boolean;
}) {
  return callFinanceHubTool('financehub_import_transactions', options);
}

/**
 * Upsert rows into a bank-product table (loans, receivables, etc.). Max 500 per call.
 */
export async function upsertFinanceHubBankProductRows(options: {
  tableSlug: string;
  rows: Array<Record<string, unknown>>;
}) {
  return callFinanceHubTool('financehub_upsert_bank_product_rows', options);
}

/**
 * Delete an account and all its transactions/sync rows (not credentials).
 */
export async function deleteFinanceHubAccount(bankId: string, accountNumber: string) {
  return callFinanceHubTool('financehub_delete_account', { bankId, accountNumber });
}

/**
 * Delete all imported data for a bankId (accounts, transactions, sync ops).
 */
export async function deleteFinanceHubImportedDataForBank(bankId: string) {
  return callFinanceHubTool('financehub_delete_imported_data_for_bank', { bankId });
}

/**
 * Delete transactions by account scope, date range, and/or ids (max 500 ids).
 */
export async function deleteFinanceHubTransactions(options: {
  accountId?: string;
  bankId?: string;
  accountNumber?: string;
  startDate?: string;
  endDate?: string;
  transactionIds?: string[];
  isCard?: boolean;
}) {
  return callFinanceHubTool('financehub_delete_transactions', options);
}

/**
 * Delete bank-product table rows by ids and/or filters (max 1000 rows).
 */
export async function deleteFinanceHubBankProductRows(options: {
  tableSlug: string;
  ids?: string[];
  filters?: Array<{
    column: string;
    op: '=' | '!=' | '>' | '<' | '>=' | '<=' | 'like' | 'in';
    value: string | number | Array<string | number>;
  }>;
}) {
  return callFinanceHubTool('financehub_delete_bank_product_rows', options);
}

// ==========================================
// INTERNAL KNOWLEDGE / BUSINESS IDENTITY / COMPANY RESEARCH (MCP)
// ==========================================

/**
 * Call EGDesk Internal Knowledge MCP tool (knowledge docs, business identity snapshots, company research).
 *
 * - Server: `POST {apiUrl}/internal-knowledge/tools/call`
 * - Client: `POST /__internal_knowledge_proxy` (see proxy.ts / middleware)
 */
export async function callInternalKnowledgeTool(
  toolName: string,
  args: Record<string, any> = {}
): Promise<any> {
  const body = JSON.stringify({ tool: toolName, arguments: args });

  const isServer = typeof window === 'undefined';

  let response: Response;
  if (isServer) {
    const apiUrl =
      (typeof process !== 'undefined' && process.env?.NEXT_PUBLIC_EGDESK_API_URL) ||
      EGDESK_CONFIG.apiUrl;
    response = await fetch(`${apiUrl}/internal-knowledge/tools/call`, {
      method: 'POST',
      headers: buildServerEgdeskHeaders(),
      body
    });
  } else {
    response = await apiFetch('/__internal_knowledge_proxy', {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body
    });
  }

  return parseEgdeskMcpToolResponse(response);
}

/** List internal knowledge documents for a business identity snapshot */
export async function listKnowledgeDocuments(
  snapshotId: string,
  category?: 'hierarchy' | 'process' | 'policy' | 'note'
) {
  return callInternalKnowledgeTool('knowledge_list_documents', {
    snapshotId,
    ...(category != null ? { category } : {})
  });
}

/** Get one knowledge document by ID (full markdown content) */
export async function getKnowledgeDocument(documentId: string) {
  return callInternalKnowledgeTool('knowledge_get_document', { documentId });
}

/** Search knowledge documents by text in title or content */
export async function searchKnowledgeContent(
  snapshotId: string,
  searchText: string,
  category?: 'hierarchy' | 'process' | 'policy' | 'note'
) {
  return callInternalKnowledgeTool('knowledge_search_content', {
    snapshotId,
    searchText,
    ...(category != null ? { category } : {})
  });
}

/** Get all documents of a single category for a snapshot */
export async function getKnowledgeByCategory(
  snapshotId: string,
  category: 'hierarchy' | 'process' | 'policy' | 'note'
) {
  return callInternalKnowledgeTool('knowledge_get_by_category', { snapshotId, category });
}

/** Create a new knowledge document */
export async function createKnowledgeDocument(
  snapshotId: string,
  title: string,
  category: 'hierarchy' | 'process' | 'policy' | 'note',
  content?: string
) {
  return callInternalKnowledgeTool('knowledge_create_document', {
    snapshotId,
    title,
    category,
    ...(content != null ? { content } : {})
  });
}

/** Update an existing knowledge document */
export async function updateKnowledgeDocument(
  documentId: string,
  updates: { title?: string; category?: 'hierarchy' | 'process' | 'policy' | 'note'; content?: string }
) {
  return callInternalKnowledgeTool('knowledge_update_document', { documentId, ...updates });
}

/** Delete a knowledge document */
export async function deleteKnowledgeDocument(documentId: string) {
  return callInternalKnowledgeTool('knowledge_delete_document', { documentId });
}

/** List business identity snapshots (optional brand filter) */
export async function listBusinessIdentitySnapshots(brandKey?: string) {
  return callInternalKnowledgeTool('businessidentity_list_snapshots', {
    ...(brandKey != null ? { brandKey } : {})
  });
}

/** Full snapshot by ID (identity JSON, SEO/SSL analysis, etc.) */
export async function getBusinessIdentitySnapshot(snapshotId: string) {
  return callInternalKnowledgeTool('businessidentity_get_snapshot', { snapshotId });
}

/** Company info slice from a snapshot (contact, structure, partners, industries) */
export async function getBusinessIdentityCompanyInfo(snapshotId: string) {
  return callInternalKnowledgeTool('businessidentity_get_company_info', { snapshotId });
}

/** Services and products from a snapshot */
export async function getBusinessIdentityServicesProducts(snapshotId: string) {
  return callInternalKnowledgeTool('businessidentity_get_services_products', { snapshotId });
}

/**
 * Call EGDesk Company Research MCP tool (run workflows and query saved research).
 *
 * - Server: `POST {apiUrl}/company-research/tools/call`
 * - Client: `POST /__company_research_proxy` (see proxy.ts / middleware)
 */
export async function callCompanyResearchTool(
  toolName: string,
  args: Record<string, any> = {}
): Promise<any> {
  const body = JSON.stringify({ tool: toolName, arguments: args });

  const isServer = typeof window === 'undefined';

  let response: Response;
  if (isServer) {
    const apiUrl =
      (typeof process !== 'undefined' && process.env?.NEXT_PUBLIC_EGDESK_API_URL) ||
      EGDESK_CONFIG.apiUrl;
    response = await fetch(`${apiUrl}/company-research/tools/call`, {
      method: 'POST',
      headers: buildServerEgdeskHeaders(),
      body
    });
  } else {
    response = await apiFetch('/__company_research_proxy', {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body
    });
  }

  return parseEgdeskMcpToolResponse(response);
}

/** Run full company research workflow for a domain (several minutes) */
export async function runCompanyResearch(
  domain: string,
  options: { bypassCache?: boolean; inquiryData?: Record<string, any> } = {}
) {
  return callCompanyResearchTool('companyresearch_run', { domain, ...options });
}

/** List company research records */
export async function listCompanyResearch(
  status?: 'completed' | 'failed' | 'in_progress'
) {
  return callCompanyResearchTool('companyresearch_list_all', {
    ...(status != null ? { status } : {})
  });
}

/** One company research record by ID */
export async function getCompanyResearchById(researchId: string) {
  return callCompanyResearchTool('companyresearch_get_by_id', { researchId });
}

/** Research records for a domain */
export async function getCompanyResearchByDomain(domain: string) {
  return callCompanyResearchTool('companyresearch_get_by_domain', { domain });
}

/** Most recent completed research for a domain */
export async function getLatestCompletedCompanyResearch(domain: string) {
  return callCompanyResearchTool('companyresearch_get_latest_completed', { domain });
}

/** Search company research by company name or domain */
export async function searchCompanyResearch(searchText: string) {
  return callCompanyResearchTool('companyresearch_search', { searchText });
}

// ==========================================
// BROWSER RECORDING HELPERS
// ==========================================

/**
 * Call EGDesk Browser Recording MCP tool (saved recorder tests, replay with optional dates).
 *
 * - Server: `POST {apiUrl}/browser-recording/tools/call`
 * - Client: `POST /__browser_recording_proxy` (see proxy.ts / middleware)
 */
export async function callBrowserRecordingTool(
  toolName: string,
  args: Record<string, any> = {}
): Promise<any> {
  const body = JSON.stringify({ tool: toolName, arguments: args });

  const isServer = typeof window === 'undefined';

  let response: Response;
  if (isServer) {
    const apiUrl =
      (typeof process !== 'undefined' && process.env?.NEXT_PUBLIC_EGDESK_API_URL) ||
      EGDESK_CONFIG.apiUrl;
    response = await fetch(`${apiUrl}/browser-recording/tools/call`, {
      method: 'POST',
      headers: buildServerEgdeskHeaders(),
      body
    });
  } else {
    response = await apiFetch('/__browser_recording_proxy', {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body
    });
  }

  return parseEgdeskMcpToolResponse(response);
}

/** List saved *.spec.js files in the EGDesk browser-recorder-tests output folder */
export async function listBrowserRecordingTests() {
  return callBrowserRecordingTool('browser_recording_list_saved_tests', {});
}

/** Inspect a spec: date UI, defaultReplayDates, labeledFieldReplayBlocks, etc. */
export async function getBrowserRecordingReplayOptions(testFile: string) {
  return callBrowserRecordingTool('browser_recording_get_replay_options', { testFile });
}

export type BrowserRecordingRunOptions = {
  headless?: boolean;
  /** Save headless preference for scheduled runs */
  persistHeadless?: boolean;
  startDate?: string;
  endDate?: string;
  datePickersByIndex?: string[];
  /** Per captureLabeledFields step, values in field order */
  labeledFieldFills?: (string | undefined)[][];
};

export type BrowserRecordingScheduleOptions = {
  testName?: string;
  scheduledTime?: string;
  frequencyType?: 'daily' | 'weekly' | 'monthly' | 'custom';
  dayOfWeek?: number;
  dayOfMonth?: number;
  customIntervalDays?: number;
  enabled?: boolean;
  headless?: boolean;
};

/** Replay a saved recording in Chrome (optional headless, dates + labeledFieldFills) */
export async function runBrowserRecording(
  testFile: string,
  options: BrowserRecordingRunOptions = {}
) {
  return callBrowserRecordingTool('browser_recording_run', {
    testFile,
    ...options
  });
}

/** List Playwright scheduler entries for browser recorder tests */
export async function listBrowserRecordingSchedules() {
  return callBrowserRecordingTool('browser_recording_list_schedules', {});
}

/** Get schedule for a test file, or null */
export async function getBrowserRecordingSchedule(testFile: string) {
  return callBrowserRecordingTool('browser_recording_get_schedule', { testFile });
}

/** Create or update a recurring schedule for a saved test */
export async function setBrowserRecordingSchedule(
  testFile: string,
  options: BrowserRecordingScheduleOptions = {}
) {
  return callBrowserRecordingTool('browser_recording_set_schedule', {
    testFile,
    ...options
  });
}

/** Remove scheduler entry for a test file */
export async function removeBrowserRecordingSchedule(testFile: string) {
  return callBrowserRecordingTool('browser_recording_remove_schedule', { testFile });
}

/** Pause a recurring schedule without deleting it */
export async function pauseBrowserRecordingSchedule(testFile: string) {
  return callBrowserRecordingTool('browser_recording_pause_schedule', { testFile });
}

/** Resume a paused recurring schedule */
export async function resumeBrowserRecordingSchedule(testFile: string) {
  return callBrowserRecordingTool('browser_recording_resume_schedule', { testFile });
}

export type BrowserRecordingSyncConfigOptions = {
  testFile?: string;
  scriptFolderPath?: string;
  scriptName?: string;
  targetTableId?: string;
  columnMappings?: Record<string, string>;
  headerRow?: number;
  skipBottomRows?: number;
  sheetIndex?: number;
  appliedSplits?: Array<{ originalColumn: string; dateColumn: string; numberColumn: string }>;
  uniqueKeyColumns?: string[];
  duplicateAction?: 'skip' | 'update' | 'allow' | 'replace-date-range' | 'replace-all';
  fileAction?: 'keep' | 'archive' | 'delete';
  enabled?: boolean;
  autoSyncEnabled?: boolean;
};

/** List EGDesk-Browser download folders with Excel/CSV files */
export async function listBrowserRecordingDownloadFolders() {
  return callBrowserRecordingTool('browser_recording_list_download_folders', {});
}

/** List sync-to-SQL configs for browser downloads */
export async function listBrowserRecordingSyncConfigs() {
  return callBrowserRecordingTool('browser_recording_list_sync_configs', {});
}

/** Get sync config by testFile or scriptFolderPath */
export async function getBrowserRecordingSyncConfig(opts: {
  testFile?: string;
  scriptFolderPath?: string;
}) {
  return callBrowserRecordingTool('browser_recording_get_sync_config', opts);
}

/** Create or update sync-to-DB for a browser download folder */
export async function setBrowserRecordingSyncConfig(
  opts: BrowserRecordingSyncConfigOptions
) {
  return callBrowserRecordingTool('browser_recording_set_sync_config', opts);
}

/** Remove sync config by configId, testFile, or scriptFolderPath */
export async function removeBrowserRecordingSyncConfig(opts: {
  configId?: string;
  testFile?: string;
  scriptFolderPath?: string;
}) {
  return callBrowserRecordingTool('browser_recording_remove_sync_config', opts);
}

// ==========================================
// AI CENTER (workflows, entities, relations, tags)
// ==========================================

/**
 * Call EGDesk AI Center MCP tool (workflows, Neuron Layer entities/relations/tags).
 *
 * - Server: `POST {apiUrl}/ai-center/tools/call`
 * - Client: `POST /__ai_center_proxy` (see proxy.ts / middleware)
 */
export async function callAICenterTool(
  toolName: string,
  args: Record<string, any> = {}
): Promise<any> {
  const body = JSON.stringify({ tool: toolName, arguments: args });

  const isServer = typeof window === 'undefined';

  let response: Response;
  if (isServer) {
    const apiUrl =
      (typeof process !== 'undefined' && process.env?.NEXT_PUBLIC_EGDESK_API_URL) ||
      EGDESK_CONFIG.apiUrl;
    response = await fetch(`${apiUrl}/ai-center/tools/call`, {
      method: 'POST',
      headers: buildServerEgdeskHeaders(),
      body
    });
  } else {
    response = await apiFetch('/__ai_center_proxy', {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body
    });
  }

  return parseEgdeskMcpToolResponse(response);
}

// ── Data Sources ─────────────────────────────────────────────────────────────

/**
 * List all data sources available for AI processing (user data tables, finance hub accounts,
 * business identity snapshots, company research records) with processing state.
 */
export async function listDataSources() {
  return callAICenterTool('ai_center_list_data_sources', {});
}

// ── Workflows ────────────────────────────────────────────────────────────────

/** List all AI workflows */
export async function listWorkflows() {
  return callAICenterTool('ai_center_list_workflows', {});
}

/** Get a single workflow by ID (includes action steps) */
export async function getWorkflow(id: string) {
  return callAICenterTool('ai_center_get_workflow', { id });
}

/** Create a new AI workflow */
export async function createWorkflow(data: {
  label: string;
  inputTypes: string[];
  hints: string[];
  outputTables: string[];
  actions: Array<{ actionId: string; params?: Record<string, any>; stage?: number; position?: number }>;
  status?: 'active' | 'suggested' | 'draft';
  suggestedBy?: string;
  triggerTable?: string | null;
  notify?: string[];
}) {
  return callAICenterTool('ai_center_create_workflow', data);
}

/** Update metadata fields of an existing workflow */
export async function updateWorkflow(
  id: string,
  data: {
    label?: string;
    status?: 'active' | 'suggested' | 'draft';
    inputTypes?: string[];
    hints?: string[];
    outputTables?: string[];
    triggerTable?: string | null;
  }
) {
  return callAICenterTool('ai_center_update_workflow', { id, ...data });
}

/** Change the status of a workflow */
export async function updateWorkflowStatus(
  id: string,
  status: 'active' | 'suggested' | 'draft'
) {
  return callAICenterTool('ai_center_update_workflow_status', { id, status });
}

/** Delete a workflow and all its action steps */
export async function deleteWorkflow(id: string) {
  return callAICenterTool('ai_center_delete_workflow', { id });
}

// ── Workflow notify roles ─────────────────────────────────────────────────────

/** Set which roles receive notifications for all activity on a workflow's runs */
export async function setWorkflowNotifyRoles(workflowId: string, roles: string[]) {
  return callAICenterTool('ai_center_set_workflow_notify', { workflowId, roles });
}

// ── Workflow actions ──────────────────────────────────────────────────────────

/** Append or insert an action step into a workflow */
export async function addWorkflowAction(
  workflowId: string,
  actionId: string,
  params: Record<string, any>,
  stage: number = 0,
  position: number = 0
) {
  return callAICenterTool('ai_center_add_workflow_action', { workflowId, actionId, params, stage, position });
}

/** Remove a single action step from a workflow by its row ID */
export async function removeWorkflowAction(rowId: string) {
  return callAICenterTool('ai_center_remove_workflow_action', { rowId });
}

// ── Workflow runs ─────────────────────────────────────────────────────────────

/** Start a new run of a workflow, optionally linked to a source data row */
export async function createRun(
  workflowId: string,
  inputData: Record<string, any>,
  sourceTable?: string | null,
  sourceRowId?: string | null
) {
  return callAICenterTool('ai_center_create_run', { workflowId, inputData, sourceTable, sourceRowId });
}

/** Get a single workflow run by ID */
export async function getRun(runId: string) {
  return callAICenterTool('ai_center_get_run', { runId });
}

/** Get all runs for a workflow */
export async function getRuns(workflowId: string) {
  return callAICenterTool('ai_center_get_runs', { workflowId });
}

/** Update the status of a workflow run */
export async function updateRunStatus(
  runId: string,
  status: '정상진행중' | '반려중' | '정상완료' | '취소완료'
) {
  return callAICenterTool('ai_center_update_run_status', { runId, status });
}

/** Advance a workflow run to a new stage */
export async function advanceRunStage(runId: string, stage: number) {
  return callAICenterTool('ai_center_advance_run_stage', { runId, stage });
}

// ── Workflow approvals ────────────────────────────────────────────────────────

/** Create a pending approval record for a run */
export async function createApproval(
  runId: string,
  stage: number,
  chainPosition: number,
  role: string
) {
  return callAICenterTool('ai_center_create_approval', { runId, stage, chainPosition, role });
}

/** Get all approval records for a run */
export async function getApprovals(runId: string) {
  return callAICenterTool('ai_center_get_approvals', { runId });
}

/** Record an approval decision */
export async function recordApprovalDecision(
  approvalId: string,
  decision: 'approved' | 'rejected' | 'cancelled'
) {
  return callAICenterTool('ai_center_record_approval_decision', { approvalId, decision });
}

// ── Entities ──────────────────────────────────────────────────────────────────

/** List all Neuron Layer entities, optionally filtered by type */
export async function listEntities(types?: string[]) {
  return callAICenterTool('ai_center_list_entities', types ? { types } : {});
}

/** Create a new entity in the Neuron Layer */
export async function createEntity(data: {
  type: string;
  name: string;
  source: 'ai' | 'human';
  id?: string;
  raw?: string;
  confidence?: number;
}) {
  return callAICenterTool('ai_center_create_entity', data);
}

/** Delete an entity from the Neuron Layer */
export async function deleteEntity(id: string) {
  return callAICenterTool('ai_center_delete_entity', { id });
}

// ── Relations ─────────────────────────────────────────────────────────────────

/** List all relations, optionally filtered by source entity ID */
export async function listRelations(fromId?: string) {
  return callAICenterTool('ai_center_list_relations', fromId ? { fromId } : {});
}

/** Create a relation edge between two entities */
export async function createRelation(data: {
  from_type: string;
  from_id: string;
  to_type: string;
  to_id: string;
  relation: string;
  source: 'ai' | 'human';
  id?: string;
  confidence?: number;
}) {
  return callAICenterTool('ai_center_create_relation', data);
}

/** Delete a relation edge by ID */
export async function deleteRelation(id: string) {
  return callAICenterTool('ai_center_delete_relation', { id });
}

// ── Tags ──────────────────────────────────────────────────────────────────────

/** List all tags, optionally filtered by entity ID */
export async function listTags(entityId?: string) {
  return callAICenterTool('ai_center_list_tags', entityId ? { entityId } : {});
}

/** Create a tag/property on an entity or document */
export async function createTag(data: {
  doc_type: string;
  doc_id: string;
  namespace: string;
  value: string;
  source: 'ai' | 'human';
  id?: string;
  doc_ref?: string;
  entity_id?: string;
  confidence?: number;
}) {
  return callAICenterTool('ai_center_create_tag', data);
}

/** Delete a tag by ID */
export async function deleteTag(id: string) {
  return callAICenterTool('ai_center_delete_tag', { id });
}

/** List all company-wide shared business deadlines from the company calendar (company_calendar table). */
export async function getCalendarEventsFromAICenter() {
  return callAICenterTool('ai_center_get_calendar_events', {});
}

/** Update the status of an operational task. */
export async function completeTask(taskId: string, status: 'completed' | 'approved' | 'rejected') {
  return callAICenterTool('ai_center_complete_task', { taskId, status });
}

// ==========================================
// KOREAN LAW / LAWYER (MCP)
// ==========================================

/**
 * Call EGDesk Korean Law MCP tool (법제처 API — laws, precedents, admin rules, municipal ordinances).
 *
 * - Server: `POST {apiUrl}/korean-law/tools/call`
 * - Client: `POST /__korean_law_proxy` (see proxy.ts / middleware)
 */
export async function callKoreanLawTool(
  toolName: string,
  args: Record<string, any> = {}
): Promise<any> {
  const body = JSON.stringify({ tool: toolName, arguments: args });

  const isServer = typeof window === 'undefined';

  let response: Response;
  if (isServer) {
    const apiUrl =
      (typeof process !== 'undefined' && process.env?.NEXT_PUBLIC_EGDESK_API_URL) ||
      EGDESK_CONFIG.apiUrl;
    response = await fetch(`${apiUrl}/korean-law/tools/call`, {
      method: 'POST',
      headers: buildServerEgdeskHeaders(),
      body
    });
  } else {
    response = await apiFetch('/__korean_law_proxy', {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body
    });
  }

  return parseEgdeskMcpToolResponse(response);
}

/** Search laws, precedents, administrative rules, or municipal ordinances */
export async function searchKoreanLaw(
  query: string,
  options: {
    target?: 'law' | 'prec' | 'admrul' | 'ordin';
    display?: number;
    page?: number;
  } = {}
) {
  return callKoreanLawTool('korean_law_search', { query, ...options });
}

/** Get full text of a law, administrative rule, or municipal ordinance */
export async function getKoreanLawText(
  id: string,
  target: 'law' | 'admrul' | 'ordin' = 'law'
) {
  return callKoreanLawTool('korean_law_get_text', { id, target });
}

/** Get full text of a court precedent (판례) */
export async function getKoreanLawDecision(id: string) {
  return callKoreanLawTool('korean_law_get_decision', { id });
}

// ==========================================
// SEO (MCP)
// ==========================================

/**
 * Call EGDesk SEO MCP tool (Lighthouse audits and report history).
 *
 * - Server: `POST {apiUrl}/seo/tools/call`
 * - Client: `POST /__seo_proxy` (see proxy.ts / middleware)
 */
export async function callSeoTool(
  toolName: string,
  args: Record<string, any> = {}
): Promise<any> {
  const body = JSON.stringify({ tool: toolName, arguments: args });

  const isServer = typeof window === 'undefined';

  let response: Response;
  if (isServer) {
    const apiUrl =
      (typeof process !== 'undefined' && process.env?.NEXT_PUBLIC_EGDESK_API_URL) ||
      EGDESK_CONFIG.apiUrl;
    response = await fetch(`${apiUrl}/seo/tools/call`, {
      method: 'POST',
      headers: buildServerEgdeskHeaders(),
      body
    });
  } else {
    response = await apiFetch('/__seo_proxy', {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body
    });
  }

  return parseEgdeskMcpToolResponse(response);
}

/** Run Lighthouse audits on one or more URLs (max 5; ~30–60s per URL) */
export async function runLighthouse(
  urls: string[],
  options: {
    proxy?: string;
    includeAiExplanation?: boolean;
  } = {}
) {
  return callSeoTool('seo_run_lighthouse', { urls, ...options });
}

/** List saved SEO Lighthouse report summaries */
export async function listSeoReports(options: { url?: string; limit?: number } = {}) {
  return callSeoTool('seo_list_reports', options);
}

/** Get a saved SEO report by ID */
export async function getSeoReport(id: string) {
  return callSeoTool('seo_get_report', { id });
}

/** Get Lighthouse issues grouped by category for a saved report */
export async function getSeoIssuesSummary(reportId: string) {
  return callSeoTool('seo_get_issues_summary', { reportId });
}

// ==========================================
// SSL (MCP)
// ==========================================

/**
 * Call EGDesk SSL MCP tool (TLS/security analysis and certificate management).
 *
 * - Server: `POST {apiUrl}/ssl/tools/call`
 * - Client: `POST /__ssl_proxy` (see proxy.ts / middleware)
 */
export async function callSslTool(
  toolName: string,
  args: Record<string, any> = {}
): Promise<any> {
  const body = JSON.stringify({ tool: toolName, arguments: args });

  const isServer = typeof window === 'undefined';

  let response: Response;
  if (isServer) {
    const apiUrl =
      (typeof process !== 'undefined' && process.env?.NEXT_PUBLIC_EGDESK_API_URL) ||
      EGDESK_CONFIG.apiUrl;
    response = await fetch(`${apiUrl}/ssl/tools/call`, {
      method: 'POST',
      headers: buildServerEgdeskHeaders(),
      body
    });
  } else {
    response = await apiFetch('/__ssl_proxy', {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body
    });
  }

  return parseEgdeskMcpToolResponse(response);
}

/** Full SSL/security audit: cert, headers, and letter grade (A+ to F) */
export async function analyzeSslSite(url: string, save: boolean = true) {
  return callSslTool('ssl_analyze_site', { url, save });
}

/** Inspect TLS certificate for a URL (expiry, issuer, SANs) */
export async function checkSslCertificate(url: string) {
  return callSslTool('ssl_check_certificate', { url });
}

/** Check security headers (HSTS, CSP, X-Frame-Options, etc.) */
export async function checkSecurityHeaders(url: string) {
  return callSslTool('ssl_check_security_headers', { url });
}

/** List saved SSL analysis history entries */
export async function listSslAnalyses(options: { websiteUrl?: string; limit?: number } = {}) {
  return callSslTool('ssl_list_analyses', options);
}

/** Get a saved SSL analysis by ID */
export async function getSslAnalysis(id: string) {
  return callSslTool('ssl_get_analysis', { id });
}

/** List stored SSL certificates (metadata only, no private keys) */
export async function listSslCertificates() {
  return callSslTool('ssl_list_certificates', {});
}

/** Get stored certificate metadata by ID */
export async function getSslCertificate(id: string) {
  return callSslTool('ssl_get_certificate', { id });
}

/** Generate a self-signed certificate for local development */
export async function generateSelfSignedCertificate(domain: string) {
  return callSslTool('ssl_generate_self_signed', { domain });
}

/** Generate a mkcert-trusted local development certificate (macOS) */
export async function generateTrustedLocalCertificate(domain: string = 'egdesk.local') {
  return callSslTool('ssl_generate_trusted_local', { domain });
}

/** Request a Let's Encrypt certificate via ACME HTTP-01 */
export async function generateLetsEncryptCertificate(domain: string, email?: string) {
  return callSslTool('ssl_generate_lets_encrypt', { domain, email });
}

/** Set the active certificate used by EGDesk dev servers */
export async function setActiveSslCertificate(certificateId: string | null) {
  return callSslTool('ssl_set_active_certificate', { certificateId });
}

/** Delete a stored certificate by ID */
export async function deleteSslCertificate(id: string) {
  return callSslTool('ssl_delete_certificate', { id });
}

// ==========================================
// Local Agent AI (MCP)
// ==========================================

/**
 * Call EGDesk Local Agent MCP tool (Ollama + Gemma 4 QAT offline inference).
 *
 * Pairs with filesystem MCP (discover/read files) and file-conversion MCP (format changes).
 *
 * - Server: `POST {apiUrl}/local-agent/tools/call`
 * - Client: `POST /__local_agent_proxy` (see proxy.ts / middleware)
 */
export async function callLocalAgentTool(
  toolName: string,
  args: Record<string, any> = {}
): Promise<any> {
  const body = JSON.stringify({ tool: toolName, arguments: args });

  const isServer = typeof window === 'undefined';

  let response: Response;
  if (isServer) {
    const apiUrl =
      (typeof process !== 'undefined' && process.env?.NEXT_PUBLIC_EGDESK_API_URL) ||
      EGDESK_CONFIG.apiUrl;
    response = await fetch(`${apiUrl}/local-agent/tools/call`, {
      method: 'POST',
      headers: buildServerEgdeskHeaders(),
      body
    });
  } else {
    response = await apiFetch('/__local_agent_proxy', {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body
    });
  }

  return parseEgdeskMcpToolResponse(response);
}

/** Check Ollama status, default model install state, and attachment capabilities */
export async function getLocalAgentStatus() {
  return callLocalAgentTool('local_agent_status', {});
}

/**
 * Pull the default local agent model (Gemma 4 E4B QAT).
 * Optional `model` overrides the Ollama tag.
 */
export async function pullLocalAgentModel(model?: string) {
  return callLocalAgentTool('local_agent_pull', model ? { model } : {});
}

export type LocalAgentChatMessage = {
  role: 'system' | 'user' | 'assistant';
  content: string;
};

export type LocalAgentCallOptions = {
  messages?: LocalAgentChatMessage[];
  /** Base64 strings (raw or data URLs) */
  images?: string[];
  /** Absolute paths — images, text files, .pdf, .docx (same rules as filesystem MCP) */
  filePaths?: string[];
  systemPrompt?: string;
  model?: string;
};

/**
 * Run offline chat with the local agent.
 * Use filesystem MCP (fs_search_files, fs_read_image) to discover files first when needed.
 */
export async function callLocalAgent(prompt: string, options: LocalAgentCallOptions = {}) {
  return callLocalAgentTool('local_agent_call', { prompt, ...options });
}

// ==========================================
// PageIndex (MCP) — PDF RAG
// ==========================================

/**
 * Call EGDesk PageIndex MCP tool (vectorless PDF indexing and retrieval).
 *
 * PDF only. Use filesystem MCP to find files; file-conversion MCP to produce PDFs from other formats.
 *
 * - Server: `POST {apiUrl}/pageindex/tools/call`
 * - Client: `POST /__pageindex_proxy` (see proxy.ts / middleware)
 */
export async function callPageIndexTool(
  toolName: string,
  args: Record<string, any> = {}
): Promise<any> {
  const body = JSON.stringify({ tool: toolName, arguments: args });

  const isServer = typeof window === 'undefined';

  let response: Response;
  if (isServer) {
    const apiUrl =
      (typeof process !== 'undefined' && process.env?.NEXT_PUBLIC_EGDESK_API_URL) ||
      EGDESK_CONFIG.apiUrl;
    response = await fetch(`${apiUrl}/pageindex/tools/call`, {
      method: 'POST',
      headers: buildServerEgdeskHeaders(),
      body
    });
  } else {
    response = await apiFetch('/__pageindex_proxy', {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body
    });
  }

  return parseEgdeskMcpToolResponse(response);
}

/** Index a PDF and build a hierarchical PageIndex tree (30–60s; requires Gemini API key) */
export async function indexPageIndexPdf(filePath: string) {
  return callPageIndexTool('pageindex_index_document', { file_path: filePath });
}

/** List indexed PDF documents */
export async function listPageIndexDocuments() {
  return callPageIndexTool('pageindex_list_documents', {});
}

/** Get metadata for an indexed document */
export async function getPageIndexDocument(docId: string) {
  return callPageIndexTool('pageindex_get_document', { doc_id: docId });
}

/** Get hierarchical structure (titles, page ranges, summaries — no full text) */
export async function getPageIndexStructure(docId: string) {
  return callPageIndexTool('pageindex_get_structure', { doc_id: docId });
}

/** Get raw text for specific pages (e.g. pages: "5", "3,8", "5-7") */
export async function getPageIndexPages(docId: string, pages: string) {
  return callPageIndexTool('pageindex_get_pages', { doc_id: docId, pages });
}

/** Delete an indexed document */
export async function deletePageIndexDocument(docId: string) {
  return callPageIndexTool('pageindex_delete_document', { doc_id: docId });
}
