'use client';

/**
 * Visitor Google OAuth callback.
 * Generated by @egdesk/next-api-plugin.
 *
 * EGDesk completes Google/Supabase OAuth, then redirects here with ?code=
 * (a one-time EGDesk code, not a Supabase token). This page exchanges it
 * for an opaque visitor session id.
 */

import { useEffect, useState } from 'react';
import { exchangeVisitorAuthCode } from '@/egdesk-visitor-google';

export default function VisitorAuthCallbackPage() {
  const [message, setMessage] = useState('Finishing sign-in…');

  useEffect(() => {
    const params = new URLSearchParams(window.location.search);
    const code = params.get('code');
    const next = params.get('next') || '/';
    if (!code) {
      setMessage('Missing login code. Close this page and try Sign in with Google again.');
      return;
    }
    void exchangeVisitorAuthCode(code)
      .then(() => {
        const dest = next.startsWith('/') ? next : '/';
        window.location.replace(dest);
      })
      .catch((err: unknown) => {
        const text = err instanceof Error ? err.message : String(err);
        setMessage('Sign-in failed: ' + text);
      });
  }, []);

  return (
    <main style={{ fontFamily: 'system-ui, sans-serif', padding: 24 }}>
      <p>{message}</p>
    </main>
  );
}
