import { NextResponse } from 'next/server';
import type { NextRequest } from 'next/server';

/**
 * EGDesk Database Proxy (Next.js 16+)
 *
 * Intercepts __user_data_proxy, __browser_recording_proxy, __internal_knowledge_proxy, __company_research_proxy, __ai_center_proxy, __korean_law_proxy, __seo_proxy, __ssl_proxy, __local_agent_proxy, __pageindex_proxy, __drive_proxy, __sheets_proxy, __docs_proxy, __slides_proxy, __egdesk_http_proxy, __gmail_proxy, __apps_script_proxy, __knowledge_wiki_proxy, __egdesk_config_proxy, __ai_caller_proxy, __kakao_proxy, __phone_proxy, __instagram_proxy, __financehub_proxy, __blog_proxy, __youtube_proxy, __visitor_auth_proxy, and __visitor_google_proxy requests
 * and forwards them to the EGDesk MCP HTTP server. This avoids CORS in local and tunneled environments.
 *
 * Generated by @egdesk/next-api-plugin
 */

/** Build EGDesk routing headers from env vars (injected into every upstream call). */
function buildEgdeskHeaders(): Record<string, string> {
  const headers: Record<string, string> = { 'Content-Type': 'application/json' };
  const apiKey = process.env.NEXT_PUBLIC_EGDESK_API_KEY;
  const projectId = process.env.NEXT_PUBLIC_EGDESK_PROJECT_ID;
  const egdeskEnv = process.env.NEXT_PUBLIC_EGDESK_ENV;
  if (apiKey) headers['X-Api-Key'] = apiKey;
  if (projectId) headers['X-EGDesk-Project-Id'] = projectId;
  if (egdeskEnv) headers['X-EGDesk-Env'] = egdeskEnv;
  return headers;
}

/** Forward this site's origin so EGDesk can bind visitor sessions to this site only. */
function visitorForwardHeaders(request: NextRequest): Record<string, string> {
  const headers = buildEgdeskHeaders();
  const origin = request.headers.get('origin') || request.nextUrl.origin;
  headers['Origin'] = origin;
  headers['X-Visitor-Origin'] = origin;
  return headers;
}

export async function proxy(request: NextRequest) {
  const { pathname } = request.nextUrl;

  // Intercept __user_data_proxy requests
  if (pathname.includes('__user_data_proxy')) {
    try {
      const body = await request.text();
      const apiUrl = process.env.NEXT_PUBLIC_EGDESK_API_URL || 'http://localhost:8080';

      // Forward to EGDesk MCP server
      const response = await fetch(`${apiUrl}/user-data/tools/call`, {
        method: 'POST',
        headers: buildEgdeskHeaders(),
        body,
      });

      const result = await response.json();

      return NextResponse.json(result, { status: response.status });
    } catch (error: any) {
      return NextResponse.json(
        { error: 'Proxy error', message: error.message },
        { status: 500 }
      );
    }
  }

  if (pathname.includes('__browser_recording_proxy')) {
    try {
      const body = await request.text();
      const apiUrl = process.env.NEXT_PUBLIC_EGDESK_API_URL || 'http://localhost:8080';

      const response = await fetch(`${apiUrl}/browser-recording/tools/call`, {
        method: 'POST',
        headers: buildEgdeskHeaders(),
        body,
      });

      const result = await response.json();

      return NextResponse.json(result, { status: response.status });
    } catch (error: any) {
      return NextResponse.json(
        { error: 'Proxy error', message: error.message },
        { status: 500 }
      );
    }
  }

  if (pathname.includes('__internal_knowledge_proxy')) {
    try {
      const body = await request.text();
      const apiUrl = process.env.NEXT_PUBLIC_EGDESK_API_URL || 'http://localhost:8080';

      const response = await fetch(`${apiUrl}/internal-knowledge/tools/call`, {
        method: 'POST',
        headers: buildEgdeskHeaders(),
        body,
      });

      const result = await response.json();

      return NextResponse.json(result, { status: response.status });
    } catch (error: any) {
      return NextResponse.json(
        { error: 'Proxy error', message: error.message },
        { status: 500 }
      );
    }
  }

  if (pathname.includes('__ai_center_proxy')) {
    try {
      const body = await request.text();
      const apiUrl = process.env.NEXT_PUBLIC_EGDESK_API_URL || 'http://localhost:8080';

      const response = await fetch(`${apiUrl}/ai-center/tools/call`, {
        method: 'POST',
        headers: buildEgdeskHeaders(),
        body,
      });

      const result = await response.json();

      return NextResponse.json(result, { status: response.status });
    } catch (error: any) {
      return NextResponse.json(
        { error: 'Proxy error', message: error.message },
        { status: 500 }
      );
    }
  }

  if (pathname.includes('__korean_law_proxy')) {
    try {
      const body = await request.text();
      const apiUrl = process.env.NEXT_PUBLIC_EGDESK_API_URL || 'http://localhost:8080';

      const response = await fetch(`${apiUrl}/korean-law/tools/call`, {
        method: 'POST',
        headers: buildEgdeskHeaders(),
        body,
      });

      const result = await response.json();

      return NextResponse.json(result, { status: response.status });
    } catch (error: any) {
      return NextResponse.json(
        { error: 'Proxy error', message: error.message },
        { status: 500 }
      );
    }
  }

  if (pathname.includes('__seo_proxy')) {
    try {
      const body = await request.text();
      const apiUrl = process.env.NEXT_PUBLIC_EGDESK_API_URL || 'http://localhost:8080';

      const response = await fetch(`${apiUrl}/seo/tools/call`, {
        method: 'POST',
        headers: buildEgdeskHeaders(),
        body,
      });

      const result = await response.json();

      return NextResponse.json(result, { status: response.status });
    } catch (error: any) {
      return NextResponse.json(
        { error: 'Proxy error', message: error.message },
        { status: 500 }
      );
    }
  }

  if (pathname.includes('__ssl_proxy')) {
    try {
      const body = await request.text();
      const apiUrl = process.env.NEXT_PUBLIC_EGDESK_API_URL || 'http://localhost:8080';

      const response = await fetch(`${apiUrl}/ssl/tools/call`, {
        method: 'POST',
        headers: buildEgdeskHeaders(),
        body,
      });

      const result = await response.json();

      return NextResponse.json(result, { status: response.status });
    } catch (error: any) {
      return NextResponse.json(
        { error: 'Proxy error', message: error.message },
        { status: 500 }
      );
    }
  }

  if (pathname.includes('__company_research_proxy')) {
    try {
      const body = await request.text();
      const apiUrl = process.env.NEXT_PUBLIC_EGDESK_API_URL || 'http://localhost:8080';

      const response = await fetch(`${apiUrl}/company-research/tools/call`, {
        method: 'POST',
        headers: buildEgdeskHeaders(),
        body,
      });

      const result = await response.json();

      return NextResponse.json(result, { status: response.status });
    } catch (error: any) {
      return NextResponse.json(
        { error: 'Proxy error', message: error.message },
        { status: 500 }
      );
    }
  }

  if (pathname.includes('__local_agent_proxy')) {
    try {
      const body = await request.text();
      const apiUrl = process.env.NEXT_PUBLIC_EGDESK_API_URL || 'http://localhost:8080';

      const response = await fetch(`${apiUrl}/local-agent/tools/call`, {
        method: 'POST',
        headers: buildEgdeskHeaders(),
        body,
      });

      const result = await response.json();

      return NextResponse.json(result, { status: response.status });
    } catch (error: any) {
      return NextResponse.json(
        { error: 'Proxy error', message: error.message },
        { status: 500 }
      );
    }
  }

  if (pathname.includes('__pageindex_proxy')) {
    try {
      const body = await request.text();
      const apiUrl = process.env.NEXT_PUBLIC_EGDESK_API_URL || 'http://localhost:8080';

      const response = await fetch(`${apiUrl}/pageindex/tools/call`, {
        method: 'POST',
        headers: buildEgdeskHeaders(),
        body,
      });

      const result = await response.json();

      return NextResponse.json(result, { status: response.status });
    } catch (error: any) {
      return NextResponse.json(
        { error: 'Proxy error', message: error.message },
        { status: 500 }
      );
    }
  }

  if (pathname.includes('__drive_proxy')) {
    try {
      const body = await request.text();
      const apiUrl = process.env.NEXT_PUBLIC_EGDESK_API_URL || 'http://localhost:8080';

      const response = await fetch(`${apiUrl}/drive/tools/call`, {
        method: 'POST',
        headers: buildEgdeskHeaders(),
        body,
      });

      const result = await response.json();

      return NextResponse.json(result, { status: response.status });
    } catch (error: any) {
      return NextResponse.json(
        { error: 'Proxy error', message: error.message },
        { status: 500 }
      );
    }
  }

  if (pathname.includes('__docs_proxy')) {
    try {
      const body = await request.text();
      const apiUrl = process.env.NEXT_PUBLIC_EGDESK_API_URL || 'http://localhost:8080';

      const response = await fetch(`${apiUrl}/docs/tools/call`, {
        method: 'POST',
        headers: buildEgdeskHeaders(),
        body,
      });

      const result = await response.json();

      return NextResponse.json(result, { status: response.status });
    } catch (error: any) {
      return NextResponse.json(
        { error: 'Proxy error', message: error.message },
        { status: 500 }
      );
    }
  }

  if (pathname.includes('__slides_proxy')) {
    try {
      const body = await request.text();
      const apiUrl = process.env.NEXT_PUBLIC_EGDESK_API_URL || 'http://localhost:8080';

      const response = await fetch(`${apiUrl}/slides/tools/call`, {
        method: 'POST',
        headers: buildEgdeskHeaders(),
        body,
      });

      const result = await response.json();

      return NextResponse.json(result, { status: response.status });
    } catch (error: any) {
      return NextResponse.json(
        { error: 'Proxy error', message: error.message },
        { status: 500 }
      );
    }
  }

  if (pathname.includes('__sheets_proxy')) {
    try {
      const body = await request.text();
      const apiUrl = process.env.NEXT_PUBLIC_EGDESK_API_URL || 'http://localhost:8080';

      const response = await fetch(`${apiUrl}/sheets/tools/call`, {
        method: 'POST',
        headers: buildEgdeskHeaders(),
        body,
      });

      const result = await response.json();

      return NextResponse.json(result, { status: response.status });
    } catch (error: any) {
      return NextResponse.json(
        { error: 'Proxy error', message: error.message },
        { status: 500 }
      );
    }
  }

  if (pathname.includes('__egdesk_http_proxy')) {
    try {
      const payload = await request.json().catch(() => ({} as Record<string, unknown>));
      const allowed = new Set(['/sheets/sync', '/drive/sync', '/apps-script/sync']);
      const targetPath = typeof payload.path === 'string' ? payload.path.split('?')[0] : '';
      if (!allowed.has(targetPath)) {
        return NextResponse.json({ error: 'Path not allowed', path: targetPath }, { status: 400 });
      }
      const method = payload.method === 'POST' ? 'POST' : 'GET';
      const apiUrl = process.env.NEXT_PUBLIC_EGDESK_API_URL || 'http://localhost:8080';
      const base = apiUrl.endsWith('/') ? apiUrl : `${apiUrl}/`;
      const url = new URL(targetPath.startsWith('/') ? targetPath.slice(1) : targetPath, base);
      const query = payload.query && typeof payload.query === 'object' ? payload.query as Record<string, unknown> : {};
      for (const [key, value] of Object.entries(query)) {
        if (typeof value === 'string' && value) url.searchParams.set(key, value);
      }
      const response = await fetch(url.toString(), {
        method,
        headers: buildEgdeskHeaders(),
        body: method === 'POST' ? JSON.stringify(payload.body || {}) : undefined,
      });
      const result = await response.json();
      return NextResponse.json(result, { status: response.status });
    } catch (error: any) {
      return NextResponse.json(
        { error: 'Proxy error', message: error.message },
        { status: 500 }
      );
    }
  }

  if (pathname.includes('__gmail_proxy')) {
    try {
      const body = await request.text();
      const apiUrl = process.env.NEXT_PUBLIC_EGDESK_API_URL || 'http://localhost:8080';
      const response = await fetch(`${apiUrl}/gmail/tools/call`, {
        method: 'POST',
        headers: buildEgdeskHeaders(),
        body,
      });
      const result = await response.json();
      return NextResponse.json(result, { status: response.status });
    } catch (error: any) {
      return NextResponse.json(
        { error: 'Proxy error', message: error.message },
        { status: 500 }
      );
    }
  }

  if (pathname.includes('__apps_script_proxy')) {
    try {
      const body = await request.text();
      const apiUrl = process.env.NEXT_PUBLIC_EGDESK_API_URL || 'http://localhost:8080';
      const response = await fetch(`${apiUrl}/apps-script/tools/call`, {
        method: 'POST',
        headers: buildEgdeskHeaders(),
        body,
      });
      const result = await response.json();
      return NextResponse.json(result, { status: response.status });
    } catch (error: any) {
      return NextResponse.json(
        { error: 'Proxy error', message: error.message },
        { status: 500 }
      );
    }
  }

  if (pathname.includes('__knowledge_wiki_proxy')) {
    try {
      const body = await request.text();
      const apiUrl = process.env.NEXT_PUBLIC_EGDESK_API_URL || 'http://localhost:8080';

      const response = await fetch(`${apiUrl}/knowledge-wiki/tools/call`, {
        method: 'POST',
        headers: buildEgdeskHeaders(),
        body,
      });

      const result = await response.json();

      return NextResponse.json(result, { status: response.status });
    } catch (error: any) {
      return NextResponse.json(
        { error: 'Proxy error', message: error.message },
        { status: 500 }
      );
    }
  }

  if (pathname.includes('__kakao_proxy')) {
    try {
      const body = await request.text();
      const apiUrl = process.env.NEXT_PUBLIC_EGDESK_API_URL || 'http://localhost:8080';

      const response = await fetch(`${apiUrl}/kakao/tools/call`, {
        method: 'POST',
        headers: buildEgdeskHeaders(),
        body,
      });

      const result = await response.json();

      return NextResponse.json(result, { status: response.status });
    } catch (error: any) {
      return NextResponse.json(
        { error: 'Proxy error', message: error.message },
        { status: 500 }
      );
    }
  }

  if (pathname.includes('__phone_proxy')) {
    try {
      const body = await request.text();
      const apiUrl = process.env.NEXT_PUBLIC_EGDESK_API_URL || 'http://localhost:8080';

      const response = await fetch(`${apiUrl}/phone/tools/call`, {
        method: 'POST',
        headers: buildEgdeskHeaders(),
        body,
      });

      const result = await response.json();

      return NextResponse.json(result, { status: response.status });
    } catch (error: any) {
      return NextResponse.json(
        { error: 'Proxy error', message: error.message },
        { status: 500 }
      );
    }
  }

  if (pathname.includes('__instagram_proxy')) {
    try {
      const body = await request.text();
      const apiUrl = process.env.NEXT_PUBLIC_EGDESK_API_URL || 'http://localhost:8080';

      const response = await fetch(`${apiUrl}/instagram/tools/call`, {
        method: 'POST',
        headers: buildEgdeskHeaders(),
        body,
      });

      const result = await response.json();

      return NextResponse.json(result, { status: response.status });
    } catch (error: any) {
      return NextResponse.json(
        { error: 'Proxy error', message: error.message },
        { status: 500 }
      );
    }
  }

  if (pathname.includes('__egdesk_config_proxy')) {
    try {
      const body = await request.text();
      const apiUrl = process.env.NEXT_PUBLIC_EGDESK_API_URL || 'http://localhost:8080';

      const response = await fetch(`${apiUrl}/egdesk-config/tools/call`, {
        method: 'POST',
        headers: buildEgdeskHeaders(),
        body,
      });

      const result = await response.json();

      return NextResponse.json(result, { status: response.status });
    } catch (error: any) {
      return NextResponse.json(
        { error: 'Proxy error', message: error.message },
        { status: 500 }
      );
    }
  }

  if (pathname.includes('__ai_caller_proxy')) {
    try {
      const body = await request.text();
      const apiUrl = process.env.NEXT_PUBLIC_EGDESK_API_URL || 'http://localhost:8080';

      const response = await fetch(`${apiUrl}/ai-caller/tools/call`, {
        method: 'POST',
        headers: buildEgdeskHeaders(),
        body,
      });

      const result = await response.json();

      return NextResponse.json(result, { status: response.status });
    } catch (error: any) {
      return NextResponse.json(
        { error: 'Proxy error', message: error.message },
        { status: 500 }
      );
    }
  }

  if (pathname.includes('__financehub_proxy')) {
    try {
      const body = await request.text();
      const apiUrl = process.env.NEXT_PUBLIC_EGDESK_API_URL || 'http://localhost:8080';

      const response = await fetch(`${apiUrl}/financehub/tools/call`, {
        method: 'POST',
        headers: buildEgdeskHeaders(),
        body,
      });

      const result = await response.json();

      return NextResponse.json(result, { status: response.status });
    } catch (error: any) {
      return NextResponse.json(
        { error: 'Proxy error', message: error.message },
        { status: 500 }
      );
    }
  }

  if (pathname.includes('__blog_proxy')) {
    try {
      const body = await request.text();
      const apiUrl = process.env.NEXT_PUBLIC_EGDESK_API_URL || 'http://localhost:8080';

      const response = await fetch(`${apiUrl}/blog/tools/call`, {
        method: 'POST',
        headers: buildEgdeskHeaders(),
        body,
      });

      const result = await response.json();

      return NextResponse.json(result, { status: response.status });
    } catch (error: any) {
      return NextResponse.json(
        { error: 'Proxy error', message: error.message },
        { status: 500 }
      );
    }
  }

  if (pathname.includes('__youtube_proxy')) {
    try {
      const body = await request.text();
      const apiUrl = process.env.NEXT_PUBLIC_EGDESK_API_URL || 'http://localhost:8080';

      const response = await fetch(`${apiUrl}/youtube/tools/call`, {
        method: 'POST',
        headers: buildEgdeskHeaders(),
        body,
      });

      const result = await response.json();

      return NextResponse.json(result, { status: response.status });
    } catch (error: any) {
      return NextResponse.json(
        { error: 'Proxy error', message: error.message },
        { status: 500 }
      );
    }
  }

  if (pathname.includes('__visitor_auth_proxy')) {
    try {
      const body = await request.text();
      const apiUrl = process.env.NEXT_PUBLIC_EGDESK_API_URL || 'http://localhost:8080';

      const response = await fetch(`${apiUrl}/visitor-auth/tools/call`, {
        method: 'POST',
        headers: visitorForwardHeaders(request),
        body,
      });

      const result = await response.json();

      return NextResponse.json(result, { status: response.status });
    } catch (error: any) {
      return NextResponse.json(
        { error: 'Proxy error', message: error.message },
        { status: 500 }
      );
    }
  }

  if (pathname.includes('__visitor_google_proxy')) {
    try {
      const body = await request.text();
      const apiUrl = process.env.NEXT_PUBLIC_EGDESK_API_URL || 'http://localhost:8080';
      const headers = visitorForwardHeaders(request);
      const authorization = request.headers.get('authorization');
      if (authorization) headers['Authorization'] = authorization;

      const response = await fetch(`${apiUrl}/visitor-google/tools/call`, {
        method: 'POST',
        headers,
        body,
      });

      const result = await response.json();

      return NextResponse.json(result, { status: response.status });
    } catch (error: any) {
      return NextResponse.json(
        { error: 'Proxy error', message: error.message },
        { status: 500 }
      );
    }
  }

  // Continue to next proxy or route
  return NextResponse.next();
}

export const config = {
  matcher: [
    /*
     * Match all paths except static assets
     * The proxy function filters for __user_data_proxy / __browser_recording_proxy / __internal_knowledge_proxy / __company_research_proxy / __ai_center_proxy / __korean_law_proxy / __seo_proxy / __ssl_proxy / __local_agent_proxy / __pageindex_proxy / __drive_proxy / __sheets_proxy / __docs_proxy / __slides_proxy / __egdesk_http_proxy / __gmail_proxy / __apps_script_proxy / __knowledge_wiki_proxy / __egdesk_config_proxy / __ai_caller_proxy / __kakao_proxy / __phone_proxy / __instagram_proxy / __financehub_proxy / __blog_proxy / __youtube_proxy / __visitor_auth_proxy / __visitor_google_proxy
     */
    '/:path*',
  ],
};
